version: "3.7"

volumes:
  share_data:

services:
  mysql:
    image: mysql:5.7
    container_name: TODO_DB
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=todo
      - MYSQL_USER=random_user
      - MYSQL_PASSWORD=not_password
    volumes:
      - share_data:/var/lib/mysql
    ports:
      - 3306:3306

  php:
    depends_on:
      - mysql
    image: php:7.4.8-apache
    volumes:
      - "./:/var/www/html"
    container_name: DOTO_PHP
    restart: always
    ports:
      - 8080:80
